<?php



$BB_upraveny_clanok='   <p class='txtnadpis'>Zrod GNU</p><p><img src="imggalery/6.jpg" align="left" >V roku 1971 zaèal <a target="_blank" href="pop.php?id=6" onClick="JavaScript: newWindow = openWin( 'pop.php?id=6', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>Richard Stallman</u></a> pracova v MIT  <a target="_blank" href="pop.php?id=7" onClick="JavaScript: newWindow = openWin( 'pop.php?id=7', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>Artificial Intelligence Laboratory</u></a>. <a target="_blank" href="pop.php?id=7" onClick="JavaScript: newWindow = openWin( 'pop.php?id=7', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>AI lab</u></a> pouívalo operaènı systém ITS navrhnutı <a target="_blank" href="pop.php?id=14" onClick="JavaScript: newWindow = openWin( 'pop.php?id=14', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>hackermi</u></a> labolatória pre poèítaè Digital PDP-10. <a target="_blank" href="pop.php?id=6" onClick="JavaScript: newWindow = openWin( 'pop.php?id=6', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>Richard</u></a> bol v tıme, ktorého úlohou bolo vylepšova tento systém. V tychto dobách pojem <strong>slobodnı software</strong> ešte nexistoval ale ITS ním bol. Ktoko¾vek chcel vidie zdrojové kody, alebo ho pouíva mal tú monos. <br />

Zaèiatkom osemdesiatıch rokov, z dôvodu zastaralej stavby, prestala firma Digital vyrába PDP-10. To sposobilo, e všetky programio pre ITS boli zastaralé. Komunita <a target="_blank" href="pop.php?id=14" onClick="JavaScript: newWindow = openWin( 'pop.php?id=14', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>Hackerov</u></a> z <a target="_blank" href="pop.php?id=7" onClick="JavaScript: newWindow = openWin( 'pop.php?id=7', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>AI Labs</u></a> sa rozpadla. Väèšinu si najala firma Symbolics. V roku <font color='red'>1982</font> nakúpilo <a target="_blank" href="pop.php?id=7" onClick="JavaScript: newWindow = openWin( 'pop.php?id=7', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>laboratórium</u></a> nové PDP-10 a ich administrátori sa rozhodli poui na nich neslobodnı systém od firmi Digital namiesto ITS. <br />
Novı operaènı system mal kopu obmezeni a kopu uivatela obmezujúcich záväzkov. Pod¾a <a target="_blank" href="pop.php?id=6" onClick="JavaScript: newWindow = openWin( 'pop.php?id=6', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>Richarda</u></a>  myšlienka systému v ktorom nesmiete zdiala, alebo meni software je zlá a netická. Ak chcel uívate¾ nieèo v softwary zmeni musel o to poprosi. Ak chcel zdiela software s kolegom, stal sa pirátom. Prakticky bol uívate¾ otrokom svojho systému.<br />

<br />

<br />

<center><font color='DarkOrange'>Filozofia slobodného softwaru sa nestavia proti komercii, pokial obchod rešpektuje slobody uívate¾a.</font></center><br />
<br />
Nastali však obavy, e by zaèali proprietárne spoloènosti vklada <a target="_blank" href="pop.php?id=15" onClick="JavaScript: newWindow = openWin( 'pop.php?id=15', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>slobodnı software</u></a> do svojho neslobodného softwaru.  Z takejto kombynácie by vznikol ïa¾ší neslobodnı software. Táto skutoènos priviedla <a target="_blank" href="pop.php?id=6" onClick="JavaScript: newWindow = openWin( 'pop.php?id=6', 'Profile', 'width=360,height=250,toolbar=0,location=0,directories=0,status=0,menuBar=0,scrollBars=auto,resizable=1' ); newWindow.focus(); return false;" ><u>Richarda</u></a> k myšlienke <strong>copyleftu</strong>. Copyleft funguje podobne ako copyright ale obrátene. Namiesto aby spútal software, zaistí jeho slobodu.<br />
Vznikla licencia GPL (General Public Licence) ktorá zaistovala, e autor musí k programu spristupni aj zdrojové kódy. Ak bol software upravenı, musí by naïalej šírenı pod GPL<br />
<br />
V roku 1985 nznikla <strong>nadácia pre slobodnı software</strong>.<img src="imggalery/8.jpg" cia pre slobodnı software. Zaisovala prísun financii jednak od sponzorov i z predaja pások s Emacsom. Neskôr sa predávali aj príruèku, CD-ROMy so zdrojovımy kódmi (všetko vrámci slobody). Èoraz viac a viac ¾udí zaèalo pomáha GNU projektu."
;

echo eregi_replace( 'General', 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' ,$BB_upraveny_clanok);
?>
